version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.7-stretch
        steps:
            - checkout
            - run:
                name: Clean CircleCI
                command: |
                    rm -rf ~/.pyenv;
                    rm -rf ~/virtualenvs;
            - run:
                name: Spin up Xvfb
                command: |
                    /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset;
                    echo "export DISPLAY=:99" >> $BASH_ENV;
            - run: sudo apt-get update        
            - run: sudo apt-get install libxcb-xinerama0 libgl1-mesa-glx libegl1-mesa libxrandr2 libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6 qt5-default;
            - run:
                name: Install miniconda
                command: |
                  wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh;
                  chmod +x ~/miniconda.sh;
                  ~/miniconda.sh -b -p ~/miniconda;
                  echo "export PATH=~/miniconda/bin:$PATH" >> $BASH_ENV;
            - run:
                name: Setup Python environment
                command: |
                  conda update --yes --quiet conda;
                  conda create -n testenv --yes python=3.6 numpy scipy pip cython qt==5.9.4 matplotlib==2.2.2 pyqt==5.9.2;
                  source activate testenv;
                  pip install -U pip;
                  pip install git+https://github.com/vispy/vispy.git;
                  pip install pytest pytest-travis-fold;
                  pip install mne nibabel pandas openpyxl tensorpac xlrd;
                  conda install -c conda-forge scikit-image;
                  pip install git+https://github.com/hbldh/lspopt.git#egg=lspopt;
                  pip install sphinx sphinx-gallery==0.4.0 sphinx_bootstrap_theme lxml;
                  pip install numpydoc;
                  pip install nipype
                  pip install h5py
                  conda install graphviz pydot
                  pip install visbrain
                  python setup.py develop
            - run:
                name: Build the documentation
                command: |
                    source activate testenv;
                    cd doc
                    make clean
                    make html
                no_output_timeout: 35m
            - store_artifacts:
                path: doc/_build/html/
                destination: html
            - add_ssh_keys:
                fingerprints:
                    - "42:95:ca:f6:27:af:76:f7:eb:50:40:d0:bf:25:b0:ea"
