version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.7.11
        steps:
            - checkout
            - run:
                name: Clean CircleCI
                command: |
                    rm -rf ~/.pyenv;
                    rm -rf ~/virtualenvs;
            - run:
                name: Spin up Xvfb
                command: |
                    /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset;
                    echo "export DISPLAY=:99" >> $BASH_ENV;
            - run: sudo apt-get update        
            - run: sudo apt-get install libxcb-xinerama0 qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools 
            - run: sudo apt-get install graphviz
            - run:
                name: Setup Python environment
                command: |
                  pip install matplotlib==3.0.0
                  pip install Pillow==7.2.0
                  pip install sphinx==3.1.2
                  pip install sphinx-gallery==0.7
                  pip install sphinx_bootstrap_theme==0.7.1
                  pip install cython scipy
                  pip install mne==0.20.7
                  pip install scikit-learn
                  pip install scikit-optimize
                  pip install numpydoc
                  pip install nipype==1.5.0
                  pip install h5py
                  pip install traits==6.1.1
                  pip install visbrain
                  pip install PyQt5-sip==12.8.0
                  pip install pyqt5==5.15.0
                  python setup.py develop --user
            - run:
                name: Build the documentation
                command: |
                    cd doc
                    make clean
                    make html
                no_output_timeout: 35m
            - store_artifacts:
                path: doc/_build/html/
                destination: html
            - add_ssh_keys:
                fingerprints:
                    - "7f:6f:31:22:7d:5f:6f:80:70:43:f4:6c:14:ef:15:ed"
