version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout
            - run:
                name: Clean CircleCI
                command: |
                    rm -rf ~/.pyenv;
                    rm -rf ~/virtualenvs;
            - run:
                name: Spin up Xvfb
                command: |
                    /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset;
                    echo "export DISPLAY=:99" >> $BASH_ENV;
            - run: sudo apt-get update        
            - run: sudo apt-get install python3-pyqt5
            - run: sudo apt-get install libxcb-xinerama0
            - run:
                name: Setup Python environment
                command: |
                  pip install --user Pillow
                  pip install --user sphinx sphinx-gallery sphinx_bootstrap_theme
                  pip install cython scipy
                  pip install --upgrade mne
                  pip install scikit-learn
                  pip install scikit-optimize
                  pip install numpydoc
                  pip install nipype==1.6.1
                  pip install h5py
                  pip install pyqt5
                  pip install pydot
                  pip install visbrain
                  python setup.py develop --user
            - run:
                name: Build the documentation
                command: |
                    cd doc
                    make clean
                    make html
                no_output_timeout: 35m
            - store_artifacts:
                path: doc/_build/html/
                destination: html
            - add_ssh_keys:
                fingerprints:
                    - "42:95:ca:f6:27:af:76:f7:eb:50:40:d0:bf:25:b0:ea"
