version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.8
        steps:
            - checkout
            - run:
                name: Clean CircleCI
                command: |
                    rm -rf ~/.pyenv;
                    rm -rf ~/virtualenvs;
            - run:
                name: Spin up Xvfb
                command: |
                    /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset;
                    echo "export DISPLAY=:99" >> $BASH_ENV;
            - run:
                name: Check PyQt5
                command: LD_DEBUG=libs python -c "from PyQt5.QtWidgets import QApplication, QWidget; app = QApplication([])"
            - run:
                name: Install miniconda
                command: |
                  wget -q https://repo.continuum.io/miniconda/Miniconda3-py37_4.8.3-Linux-x86_64.sh -O ~/miniconda.sh;
                  chmod +x ~/miniconda.sh;
                  ~/miniconda.sh -b -p ~/miniconda;
                  echo "export PATH=~/miniconda/bin:$PATH" >> $BASH_ENV;
            - run:
                name: Setup Python environment
                command: |
                  QT_DEBUG_PLUGINS=1 mne sys_info
                  conda update --yes --quiet conda;
                  pip install Pillow
                  pip install sphinx sphinx-gallery sphinx_bootstrap_theme
                  pip install cython scipy
                  pip install mne==0.23.0
                  pip install scikit-learn
                  pip install scikit-optimize
                  pip install numpydoc
                  pip install nipype
                  pip install h5py
                  pip install pyqt5
                  conda install graphviz pydot
                  pip install visbrain
                  python setup.py develop --user
            - run:
                name: Build the documentation
                command: |
                    cd doc
                    make clean
                    make html
                no_output_timeout: 15m
            - store_artifacts:
                path: doc/_build/html/
                destination: html
            - add_ssh_keys:
                fingerprints:
                    - "7f:6f:31:22:7d:5f:6f:80:70:43:f4:6c:14:ef:15:ed"
